##########################################################################
# This script contains common variables used by main script, subscripts or
# specific application installation scripts.
#
# Author: César Rodríguez González
# Version: 1.3
# Last modified date (dd/mm/yyyy): 01/08/2016
# Licence: MIT
##########################################################################

# YOUR DISTRO AND SYSTEM INFO
#   Distribution name (ubuntu/debian/linuxmint)
	distro="`lsb_release -i | awk '{print $3}' | tr '[:upper:]' '[:lower:]'`"; if [ "$distro" == "linuxmint" ]; then if [ "debian" == "`lsb_release -c | awk '{print $2}'`" ]; then distro="lmde"; fi; fi
#       Distribution version name appropiate to add third-party repositories to your OS. Not necessary your distro name.
	if [ "$(lsb_release -sc)" == "jessie" ]; then distroName="jessie"; else	distroName="xenial"; fi
#	Linux language
	language="${LANG:0:2}"
#	Actual date and time
	if [ "$language" == "es" ]; then snapshot=$(date +'%d-%m-%y.%Hh:%Mm:%Ss'); else snapshot=$(date +'%m-%d-%y.%Hh:%Mm:%Ss'); fi

# USER INFO
#	Username that executes the installation script
	username="`cat /tmp/linux-app-installer-username`"
#	Root homefolder associated to username
	homeFolder=`sudo -u $username -i eval 'echo $HOME'`
#	Download user folder
	homeDownloadFolder="$homeFolder/`cat $homeFolder/.config/user-dirs.dirs | grep "XDG_DOWNLOAD_DIR" | awk -F "=" '{print $2}' | tr -d '"' | awk -F "/" '{print $2}'`"

# SCRIPTS FOLDERS
#	Main script root folder
	scriptRootFolder="`cat /tmp/linux-app-installer-scriptRootFolder`"
#	Folder that will contain the script's log file.
	logsFolder="$homeFolder/logs"
#	Temporal folder used by installation script.
	tempFolder="/tmp/linux-app-installer-$snapshot"
#	Folder where are placed files which contain commands to add third-party repositories.
	thirdPartyRepoFolder="$scriptRootFolder/third-party-repo"
#	Folder where are placed files which contain commands to set debconf for EULA support.
	eulaFolder="$scriptRootFolder/eula"
#	Folder where are placed files which contain commands to prepare the installation of application packages.
	preInstallationFolder="$scriptRootFolder/pre-installation"
#	Folder where are placed files which contain commands to setup application that have been installed.
	postInstallationFolder="$scriptRootFolder/post-installation"
#	Foldet where are placed files which contain commands to install non-repo apps.
	nonRepositoryAppsFolder="$scriptRootFolder/non-repository-apps"
# 	Folder where are placed icons used by main script.
	installerIconFolder="$scriptRootFolder/icons/installer"


# SCRIPTS FILES
#	Translation file
	languageFile="$scriptRootFolder/languages/$language.properties"
#	File that contains categories, applications and packages used by main menu and the installation proccess.
	appListFile="$scriptRootFolder/applist/applicationList.$distro"
#	Log file where the script will report errors or steps of installation process.
	logFile="$logsFolder/$snapshot-`cat /tmp/linux-app-installer-logFilename`"
#	Script that launchs a zenity to ask por admin password.
	askpass="$tempFolder/askpass.sh"


# MENU WINDOWS INFO
#	Interface used for Debconf (Dialog - Terminal mode / Zenity - Desktop mode)
	if [ -z $DISPLAY ]; then debconfInterface="Dialog"; else if [ "$KDE_FULL_SESSION" != "true" ]; then debconfInterface="Gnome"; else debconfInterface="Kde"; fi; fi
#	Width/Height in pixels of dialog box (on terminal mode)
	dialogWidth=$((`tput cols` - 4))
	dialogHeight=$((`tput lines` - 6))
#	Width/Height in pixels of windows (on desktop mode)
	zenityWidth=770
	zenityHeight=400

# SCRIPT COMMANDS GENERATED BY MAIN SCRIPT
#	Commands to add third-party repotitories.
	repoCommands=""
#	Commands to be executed before installing an application.
	preInstallationCommands=""
#	Commands to install packages of applications from default repositories.
	packageCommands=""
#	Commands to install non-repository applications.
	nonRepoAppCommands=""
#	Commands to be executed after the installation of an application.
	postInstallationCommands=""

